### ISSUE TITLE
Unable to load class 'org.objectweb.asm.util.TraceClassVisitor'.

### ISSUE THREAD

**Issue by SulfuricM** [architectury/architectury-loom#134] opened 2023-05-31 17:30 UTC
Minecraft 1.16.5
ArcLoom 1.2
Only Forge and Mixin
ArcLoom 1.1 There is no such problem
[I use machine translation]

**Comment by Juuxel** [comment] 2023-05-31 17:57
Duplicate of #132.

**Closed as not planned by Juuxel** 2023-05-31 17:57 UTC
Labels: bug, duplicate, Forge
